/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTA1 (number 35), Magnet
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Magnet_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Magnet_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Magnet_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Magnet_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Magnet_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC8 (number 80), DIR_X
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIR_X_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIR_X_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DIR_X_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DIR_X_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIR_X_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC9 (number 81), DIR_Y
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIR_Y_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIR_Y_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DIR_Y_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DIR_Y_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIR_Y_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC10 (number 82), DIR_Z
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIR_Z_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIR_Z_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DIR_Z_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DIR_Z_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIR_Z_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC11 (number 83), DIR_PHI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIR_PHI_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIR_PHI_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DIR_PHI_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DIR_PHI_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIR_PHI_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD0 (number 93), STEP_X
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEP_X_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEP_X_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEP_X_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEP_X_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEP_X_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD1 (number 94), STEP_Y
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEP_Y_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEP_Y_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEP_Y_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEP_Y_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEP_Y_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD2 (number 95), STEP_Z
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEP_Z_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEP_Z_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEP_Z_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEP_Z_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEP_Z_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD3 (number 96), STEP_PHI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEP_PHI_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEP_PHI_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEP_PHI_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEP_PHI_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEP_PHI_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE0 (number 1), UART1TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1TX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1TX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1TX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTE1 (number 2), UART1RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
